load_module modules/ngx_http_openhal_module.so;

events {}

http {
    openhal_bootstrap /etc/openhal/app.hal;

    server {
        listen 8080;

        location = /hello {
            openhal_content openhal.app/hello;
        }

        location = /delay {
            openhal_content openhal.app/delayed;
        }

        location /inspect {
            openhal_content openhal.app/inspect;
        }
    }
}
